server.port: 8085
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: transfer
      port: 27017
      host: localhost
  cloud:
    stream:
      function.definition: transactionProcess
      default-binder: kafka
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true
          default:
            producer:
              useNativeEncoding: true
            consumer:
              useNativeEncoding: true
          autoCreateTopics: true
          brokers: localhost:9092

      bindings:
        transactionCreated-out-0:
          destination: streaming.pix.transaction.created
          contentType: application/*+avro
          producer:
            use-native-encoding: true
        transactionProcess-in-0:
          destination: streaming.pix.transaction.process
          contentType: application/*+avro
          consumer:
            use-native-encoding: true
  kafka:
    properties:
      schema:
        registry:
          url: http://localhost:8081
